name: exemplo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.0
  #carousel_slider: 5.0.0
  carousel_slider: 4.2.1
  image_picker: ^0.8.4+4
  flutter_screenutil: ^5.3.0
  url_launcher: ^6.0.20
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adicionando assets
  assets:
    - lib/src/assets/
